import asyncio
import os
import json
from dotenv import load_dotenv
from mcp import ClientSession, StdioServerParameters
from mcp.client.stdio import stdio_client

load_dotenv()

server_params = StdioServerParameters(
    command="python",
    args=["main_mcp.py"],
    env={
        "GROQ_API_KEY": os.getenv("GROQ_API_KEY"),
        "Y_GROQ": os.getenv("Y_GROQ"),
        "J_GROQ": os.getenv("J_GROQ"),
    }
)


def show(title, result):
    print(f"\n--- {title} ---")
    print(f"is_error: {result.isError}")
    text = result.content[0].text if result.content else "(no content)"
    try:
        print(json.dumps(json.loads(text), indent=2))
    except (json.JSONDecodeError, TypeError):
        print(text)
    print("-" * 80)


async def test():
    async with stdio_client(server_params) as (read, write):
        async with ClientSession(read, write) as session:
            await session.initialize()

            tools = await session.list_tools()
            print(f"Available tools: {[t.name for t in tools.tools]}")
            print("=" * 80)

            # ---------- Happy path: each tool individually ----------

            result = await session.call_tool(
                "generate_sql",
                {"query": "Show me the 5 most recent transactions for customer CUST_DIANA_VOSS"}
            )
            show("generate_sql: basic", result)
            generated_sql = result.content[0].text  

            result = await session.call_tool(
                "execute_sql",
                {"query": "Show me the 5 most recent transactions for customer CUST_DIANA_VOSS"}
            )
            show("execute_sql: from natural language query", result)

            result = await session.call_tool(
                "execute_sql",
                {"sql": "SELECT COUNT(*) as total FROM transactions"}
            )
            show("execute_sql: raw SQL directly", result)

            result = await session.call_tool(
                "sql_to_text",
                {
                    "query": "Show me the 5 most recent transactions for customer CUST_DIANA_VOSS",
                    "sql": "SELECT * FROM transactions WHERE customer_id = 'CUST_DIANA_VOSS' ORDER BY timestamp DESC LIMIT 5",
                }
            )
            show("sql_to_text: with explicit sql", result)

            result = await session.call_tool(
                "sql_to_text",
                {"query": "Has customer CUST_DIANA_VOSS had any wire transfers over $10,000?"}
            )
            show("sql_to_text: query only, no sql (should generate internally)", result)

            result = await session.call_tool(
                "answer_question",
                {"query": "Has customer CUST_DIANA_VOSS had any wire transfers over $10,000?"}
            )
            show("answer_question: end-to-end", result)

            result = await session.call_tool(
                "retrieve_schema_context",
                {"query": "transactions table schema"}
            )
            show("retrieve_schema_context: basic", result)

            # ---------- Chained flow: reuse SQL generated by one tool in the next ----------

            result = await session.call_tool(
                "execute_sql",
                {"sql": generated_sql}
            )
            show("execute_sql: reusing SQL from generate_sql output", result)

            # ---------- Edge cases ----------

            result = await session.call_tool("generate_sql", {"query": ""})
            show("generate_sql: empty query (expect error)", result)

            result = await session.call_tool("execute_sql", {})
            show("execute_sql: no sql and no query (expect error)", result)

            result = await session.call_tool("sql_to_text", {"sql": "SELECT 1"})
            show("sql_to_text: missing required 'query' (expect error)", result)

            result = await session.call_tool(
                "execute_sql",
                {"sql": "DROP TABLE transactions"}
            )
            show("execute_sql: non-SELECT statement (expect safety-filter rejection)", result)

            result = await session.call_tool(
                "execute_sql",
                {"sql": "SELECT * FROM this_table_does_not_exist"}
            )
            show("execute_sql: invalid table name (expect graceful error, not crash)", result)

            result = await session.call_tool(
                "unknown_tool_name",
                {"query": "test"}
            )
            show("unknown tool name (expect 'unknown tool' error)", result)


if __name__ == "__main__":
    asyncio.run(test())