name: PR Agent

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write

    steps:
      - name: PR Agent
        uses: the-pr-agent/pr-agent@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.PR_REVIEW_KEY  }}
          OPENAI_API_KEY: "na"                          
          config.ai_provider: "google"
          config.model: "gemini/gemini-2.0-flash"
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
